mylist = [1,2,"luffy","mugiwara"]
print(mylist)
print(mylist[2])
print(mylist[-1])
mylist.append(["zorojuro" , "sangoro"])
print(mylist)
mylist.append("blackbeard")
print(mylist)
mylist.pop()
print(mylist)
print(len(mylist))
mylist.append(5)
mylist.append(5)
mylist.append(5)
mylist.append(5)
mylist.append(5)
print(mylist.count(5))
mylist.insert(1,"yamato")
print(mylist)
mylist.pop(-1)
mylist.pop(-2)
mylist.pop(-3)
print(mylist)
print("Milan Psycho")